name: api-build

on:
  push:
    paths:
      - ".github/workflows/api-build.yml"
      - "api/**"
  workflow_dispatch: # manual

jobs:
  build:
    name: build-dotnet-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: ./api
      - run: dotnet test
        working-directory: ./api
      - name: Start API and test endpoint
        run: |
          dotnet run --project ./api &
          sleep 10
          curl -f http://localhost:5000/weatherforecast || exit 1
          pkill -f "dotnet.*api"



# *** notes:
# steps[*].working-directory: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory
# path filter globs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
